### ISSUE TITLE
updateOne function in AQL and models

### ISSUE THREAD

**Issue by john3571** [SkyPHP/skyphp#153]
For multi-process scripts which repeatedly retrieve single database records and perform work until no applicable records are available (such as with the vfolder Daemon) it would be useful for there to be an updateOne function.

updateOne would allow a developer to lock a record (with `set locked = 1`) so that other concurrent processes would not accidentally retrieve the same record as another process and perform repeat work.  The current work around is to retrieve a record object and then save it immediately with the `locked` field, however this is not atomic, and it happens often that a concurrent process grabs the same record as some other process before the original process can perform a separate `update` query to lock the record.  combining the `select` and the `update` ensures atomicity, and this problem would be avoided.

current work around:
`update set locked = 1` before the `select` : this works around the problem, but it is not atomic.

`order by random()` : this may work, however it is not ideal because there is a possibility that two simultaneous `order by random()` queries may return the same result.  The probability of this happening increases as the result set shrinks, becoming very likely when there are 3 or less records remaining to perform work.

random `sleep` time : this is not perfect and introduces extra waiting in the script which is not necessary.

**Comment by stanistan** [comment]
Example sql query w/o business logic?

**Comment by john3571** [comment]
something like:

```
UPDATE work_table 
SET locked = 1 
WHERE
    night_time_job = 1 AND
    completion_time is NULL AND
    locked is NULL
LIMIT 1
RETURNING *
```

A caller to updateOne would then perform whatever work is desired and then update the record again after work to unlock the record and mark whatever else other fields to indicate work is complete.

**Comment by stanistan** [comment]
I'm assuming this is the desired usage:

``` php
<?php

$fields = ['locked' => 1];
$clause = ['where' => ['night_time_job = 1', 'completion_time is NULL']];

// implies limit 1
$work = work_table::updateOne($fields, $clause);

```

**Comment by stanistan** [comment]
An issue that needs to be considered:

``` sql
--postgresql
UPDATE mytable SET
  mycolumn = mycolumn + 1
WHERE mykey = 'dante'
RETURNING mycolumn;
```

Is different from:

``` sql
--mysql
UPDATE mytable SET
  mycolumn = @mycolumn := mycolumn + 1
WHERE mykey = 'dante';
SELECT @mycolumn;
```

**Comment by john3571** [comment]
yes, that would be the usage.  Also, `where` needs to include `locked is NULL`.

The Postgresql vs MySQL differences could be accommodated by a hook in the function which returns the correct query depending on the given database.  This type of solution could also be implemented in other places where there are database-dependent queries being generated.  For now I think it is pretty safe to assume Postgresql usage and throw an `Exception` if the function detects MySQL or some other database is in use.

**Comment by john3571** [comment]
Postgresql does not support `UPDATE` with `LIMIT` however the equivalent is `UPDATE` with `FROM` and `WHERE` clause.  The above example I gave becomes:

``` sql
UPDATE work_table 
SET locked = 1 
FROM (
    SELECT id from work_table
    WHERE
        night_time_job = 1 AND
        completion_time is NULL AND
        locked is NULL
    LIMIT 1
    ) AS alias
WHERE work_table.id = alias.id
RETURNING *
```

**Comment by will123195** [comment]
This doesn't belong in aql or models.  SQL is the right tool for this job.
