### ISSUE TITLE
update() & insert()

### ISSUE THREAD

**Issue by will123195** [SkyPHP/skyphp#160]
- Need `update()` (alias of `saveProperties()`)
- Need `insert()`

**Comment by stanistan** [comment]
Sample usage?

I feel that the two methods should have the same usage.

So if `update()` is an alias of `saveProperties()`, then both of them take an associative array of arguments.

Since these are two new methods, they should throw `\ValidationException` on failure.

``` php
<?php

$fields = array(
    'name' => 'Sleepytime Gorilla Museum'
);

$o = new artist($id);
$o->update($fields);

// ...

$artist = artist::insert($fields);

```

**Comment by stanistan** [comment]
Once only insert() and update() are used for their respective tasks, we can easily implement #142 (state).
