### ISSUE TITLE
skybox does not close if previous history state contains #

### ISSUE THREAD

**Issue by SkyPHP** [SkyPHP/skyphp#4]
example.com/abc#xyz
-- open skybox --
example.com/abc?skybox=/abc/123
-- back button --
example.com/abc#xyz   (but the skybox doesn't close)

the problem is History.Adapter.bind(window,'statechange'  does not listen for hash changes; but it appears to be a bug because the hash is not the only thing changing in the url.

**Comment by will123195** [comment]
also, if a second consecutive skybox is opened, closing it should close the skybox instead of going back and opening the first skybox.
